name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: pull docker image
        run: sudo docker pull iakv4/nextjs-demo:latest

      - name: delete old docker container
        run: sudo docker rm -f nextjs-demo-container || true

      - name: run latest docker container
        run: sudo docker run -d -p 3000:3000 --name nextjs-demo-container iakv4/nextjs-demo
